repos:
  # Linting for Bash scripts
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
  # Linting for YAML files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
  # Prettier [for YAML / JSON files]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  # Lint git commit messages (for semantic versioning benefits)
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
