# -------------------------------------------------------------------------------------------------
#                                FlowPy CI Workflow
# -------------------------------------------------------------------------------------------------
name: "ci"

# The name that is displayed on the github webpage when you drill in for details on Github Actions.
# -------------------------------------------------------------------------------------------------
run-name: >
  Continuous Integration for ${{ github.event.pull_request.title }} ${{ github.event.pull_request._links.html.href }}

# -------------------------------------------------------------------------------------------------
#                            Github Event Triggers & Automation
# -------------------------------------------------------------------------------------------------
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "28 0 * * *"
  push:
    branches: ["develop", "master"]
  pull_request:
    branches: ["develop", "master"]

# -------------------------------------------------------------------------------------------------
#                          Github Runner: Github API Permissions
# -------------------------------------------------------------------------------------------------
permissions:
  contents: read
  pull-requests: read
  packages: write

# -------------------------------------------------------------------------------------------------
#                         Github Runner: Environment Variables
# -------------------------------------------------------------------------------------------------
env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_USERNAME: ${{ github.actor }}
  IMAGE_TAG: "${{ github.event.pull_request.head.sha || github.sha }}"
  IMAGE_NAME: flowpy
  REGISTRY: ghcr.io

# -------------------------------------------------------------------------------------------------
#                                 Cooperative Constraints
# -------------------------------------------------------------------------------------------------
# Only one run per PR <- branch (last commit cancels previous)
# -------------------------------------------------------------------------------------------------
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # -----------------------------------------------------------------------------------------------
  #                               Github PR Context Extraction
  # -----------------------------------------------------------------------------------------------
  build-info:
    timeout-minutes: 10
    name: "Build Info"
    runs-on: "ubuntu-20.04"
    env:
      TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
    outputs:
      runs-on: "ubuntu-20.04"
      target-commit-sha:
        "${{steps.discover-pr-merge-commit.outputs.target-commit-sha ||
        github.event.pull_request.head.sha ||
        github.sha
        }}"
    steps:
      - name: Discover PR merge commit
        id: discover-pr-merge-commit
        run: |
          TARGET_COMMIT_SHA="$(gh api '${{ github.event.pull_request.url }}' --jq .merge_commit_sha)"
          echo "TARGET_COMMIT_SHA=$TARGET_COMMIT_SHA" >> ${GITHUB_ENV}
          echo "target-commit-sha=${TARGET_COMMIT_SHA}" >> ${GITHUB_OUTPUT}
        if: github.event_name == 'pull_request_target'
      # The labels in the event aren't updated when re-triggering the job, So lets hit the API to get
      # up-to-date values
      - name: Get latest PR labels
        id: get-latest-pr-labels
        run: |
          echo -n "pull-request-labels=" >> ${GITHUB_OUTPUT}
          gh api graphql --paginate -F node_id=${{github.event.pull_request.node_id}} -f query='
            query($node_id: ID!, $endCursor: String) {
              node(id:$node_id) {
                ... on PullRequest {
                  labels(first: 100, after: $endCursor) {
                    nodes { name }
                    pageInfo { hasNextPage endCursor }
                  }
                }
              }
            }' --jq '.data.node.labels.nodes[]' | jq --slurp -c '[.[].name]' >> ${GITHUB_OUTPUT}
        if: github.event_name == 'pull_request_target'
  # -----------------------------------------------------------------------------------------------
  #                                      Code Quality
  # -----------------------------------------------------------------------------------------------
  lint-code:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Source
        uses: actions/checkout@v1

      - name: Run ShellCheck
        uses: azohra/shell-linter@latest

      - name: Run Hadolint (Dockerfile)
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile

      - name: Lint Markdown
        uses: avto-dev/markdown-lint@v1

      - name: Lint JavaScript & YAML
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check **/*.{js,y[a]ml}
          only_changed: True
  # -----------------------------------------------------------------------------------------------
  #                                       Publishing
  # -----------------------------------------------------------------------------------------------
  publish-packages:
    name: publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build-target: develop
          - tag-name: develop
    steps:
      - name: fetch source
        uses: actions/checkout@v3

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build and push docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.build-target }}
